### ISSUE TITLE
Different p-values using stat_compare_means and compare_means with wilcox.test

### ISSUE THREAD

**Issue by parrist** [kassambara/ggpubr#193]
I'm using compare_means and stat_compare_means in ggpubr (version 0.2) to compute p-values with the Wilcoxon test, but the p-values are different. Is this the same problem as Issue #141 or is my code incorrect?

Thanks in advance.

**Input file**
```
> head(RNAseq)
             Hybridization.REF                  Cancer.type Cohort   Sample.type          gene_id       AR     ESR1
1 TCGA.BL.A0C8.01A.11R.A10U.07 Bladder urothelial carcinoma   BLCA Cancer tissue normalized_count   4.0840 220.5368
2 TCGA.BL.A13I.01A.11R.A13Y.07 Bladder urothelial carcinoma   BLCA Cancer tissue normalized_count  23.0583  67.5566
3 TCGA.BL.A13J.11A.13R.A10U.07 Bladder urothelial carcinoma   BLCA Normal tissue normalized_count 225.7053 101.7887
4 TCGA.BL.A13J.01A.11R.A10U.07 Bladder urothelial carcinoma   BLCA Cancer tissue normalized_count  10.4112  18.0462
5 TCGA.BL.A3JM.01A.12R.A21D.07 Bladder urothelial carcinoma   BLCA Cancer tissue normalized_count   1.3688  11.7720
6 TCGA.BL.A5ZZ.01A.31R.A30C.07 Bladder urothelial carcinoma   BLCA Cancer tissue normalized_count  33.9183  10.5422
     ESR2     ESRRA  ESRRB    ESRRG  HNF4A    HNF4G  NR0B1  NR0B2    NR1D1     NR1D2    NR1H2     NR1H3    NR1H4
1 23.3372 1801.6336 0.0000  18.0863 2.3337  17.5029 0.0000 3.5006 440.4026 1105.0175 1574.679 1287.0478 910.1517
2  1.6181  739.0777 2.0227   3.6408 0.0000   2.0227 0.4045 0.0000 183.4871  362.0550 1789.644  575.6472   0.8091
3  7.3760  725.7975 1.4752  59.0079 0.0000   0.0000 0.0000 0.0000 978.4252 1244.3297 2282.869  385.0267   6.6384
4 13.1876 1025.8546 1.3882   1.3882 1.3882   2.7763 0.0000 0.0000 569.7033  732.2575 1538.088  927.2948  24.9870
5 59.6811  451.1669 2.1901 358.6339 0.2738 196.8380 0.0000 0.2738 396.4191 1091.5064 1350.489  225.5835   1.3688
6 15.5841  991.4230 0.9167  88.4626 0.4584   0.9167 0.0000 1.3751 537.3302  657.2818 1856.798  390.9773   2.7501
   NR1I2    NR1I3    NR2C1     NR2C2   NR2E1  NR2E3     NR2F1     NR2F2     NR2F6     NR3C1     NR3C2      NR4A1
1 1.1669 152.3512 371.0618 1008.2905  3.5006 1.7503   86.9312 3966.1610 2709.4516  406.0677   22.1704   409.5683
2 0.8091   3.8269 264.5631  619.8786  4.8544 2.8317   80.0971  544.0939  846.2783 1060.6796    8.0906   842.6375
3 1.4752   7.8776 379.1259 1314.1140  0.0000 0.7376  280.2877 1250.9681  358.4732 1607.2285 1257.6065 16508.2058
4 5.5527  23.2657 288.7385  671.5322 15.2698 2.7763   81.2077 2258.5459 1020.9960  185.3201   23.5988  1007.8084
5 5.2016   9.3929 609.1301  867.1302  3.2852 1.3688   76.9283  310.7248 1479.7071  188.0775    8.2130   697.5566
6 3.2085   7.6316 261.7210  617.0566 55.4610 2.7501 1249.0188  856.6665  905.2522 1059.7180  200.3014 19825.2520
      NR4A2     NR4A3  NR5A1    NR5A2   NR6A1      PGR     PPARA     PPARD      PPARG      RARA     RARB      RARG
1   79.9300   37.3396 1.1669 315.0525 55.4259   8.1680 1016.3361 1720.5368 16911.9020 3145.8576  44.9242  992.4154
2  135.5178   63.1068 0.8091  46.5210  8.4951  52.1845  407.3625  856.7961   748.7864  783.1715 653.7217 1179.6117
3 1307.7632 1171.3074 0.0000  68.5967  3.6880 241.1949 1539.3694  984.6948   154.1582 1006.0852 609.2569  425.5947
4  144.3693   84.6781 0.0000  11.7994  6.9408  17.3521  849.5575 2040.6039  3033.1425  742.6687  46.5036 2165.5388
5   39.1486   28.1979 2.4639  17.7948 18.3423   3.8327  377.5238  778.8652   114.4343  502.9088 433.9196  375.3337
6 5869.7010 1876.5076 2.7501 154.9242  4.1252   8.2504  407.4781 2292.2360   170.9666 1201.3499 380.8934 1256.8109
      RORA   RORB    RORC      RXRA      RXRB    RXRG      THRA      THRB      VDR
1 187.2812 0.0000  7.5846 5279.4632  812.1354  0.0000  364.7316 1141.7736  25.0875
2  97.8964 0.0000 44.4984 2873.3819  861.2460  1.2136  269.1828   30.7443 103.1553
3 961.0916 2.2128  2.9504 3484.4182 1264.2449 22.1280 2606.3065 1688.3644  38.3552
4 149.9219 2.7763 50.6681 2085.7192  822.4883  0.0000  282.6306 2350.8589 595.5232
5 372.5960 1.0951  1.0951  475.5321  772.0211  1.3688 1322.8335   19.9849  83.2250
6 869.5004 0.9167 11.9172 1442.4449  814.4978  0.0000  679.1454   22.4594 723.7434
```

**Compare_means**
```
AR<- compare_means(AR~Sample.type, RNAseq, group.by="Cohort", method = "wilcox.test")
```

```
> head(AR)
# A tibble: 6 x 9
  Cohort .y.   group1        group2               p    p.adj p.format p.signif method  
  <chr>  <chr> <chr>         <chr>            <dbl>    <dbl> <chr>    <chr>    <chr>   
1 BLCA   AR    Cancer tissue Normal tissue 6.79e- 6 5.40e- 5 6.8e-06  ****     Wilcoxon
2 BRCA   AR    Cancer tissue Normal tissue 2.44e- 1 9.80e- 1 0.2439   ns       Wilcoxon
3 ESCA   AR    Cancer tissue Normal tissue 2.02e- 7 2.00e- 6 2.0e-07  ****     Wilcoxon
4 HNSC   AR    Cancer tissue Normal tissue 5.23e-12 7.30e-11 5.2e-12  ****     Wilcoxon
5 KIRC   AR    Cancer tissue Normal tissue 9.35e- 1 1.00e+ 0 0.9349   ns       Wilcoxon
6 KIRP   AR    Cancer tissue Normal tissue 7.50e- 1 1.00e+ 0 0.7502   ns       Wilcoxon`

**Stat_compare_means**
`ggplot(RNAseq, aes(x=Cohort, y=AR, fill=Sample.type), las = 2) + 
  geom_boxplot() +
  labs(fill = "Sample type") +
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x),
    labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  ggtitle("AR") +
  xlab(" ") +
  ylab("RNA-seq normalized RSEM") +
  stat_compare_means(comparisons = list( c("Cancer tissue", "Normal tissue"))) + # Add pairwise comparisons p-value
  stat_compare_means(label.y = 5, label = "p.format", size = 2, method = "wilcox.test") + # Add global p-value, label = "p.signif" adds stars for significance level or ns for not significant or label = "p.format" to write out the p-value
  theme_classic() +
  scale_fill_jco() + #uses the jco palette in the ggsci package
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust=0.5)) #hjust controls horizontal justification and vjust controls vertical justification (0 (left), 0.5 (center), 1 (right))
```

![Cancer vs normal - AR - pvalues](https://user-images.githubusercontent.com/52787947/61053243-7ced1680-a3ed-11e9-9744-d95c33ea47e8.jpg)

**Comment by kassambara** [comment]
This issue has been already fixed in #141 .

Please install the latest dev version:

```r
devtools::install_github("kassambara/ggpubr", dependencies = FALSE)
```

**Comment by parrist** [comment]
Installation of the dev version hasn't resolved the issue. The p-values are still slightly different for compare_means and stat_compare_means.

```
> devtools::session_info()
- Session info -----------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.6.0 (2019-04-26)
 os       Windows >= 8 x64            
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       Europe/Berlin               
 date     2019-07-12                  

- Packages ---------------------------------------------------------------------------------------------------------------------------
 package     * version   date       lib source                            
 assertthat    0.2.1     2019-03-21 [1] CRAN (R 3.6.0)                    
 backports     1.1.4     2019-04-10 [1] CRAN (R 3.6.0)                    
 callr         3.3.0     2019-07-04 [1] CRAN (R 3.6.1)                    
 cli           1.1.0     2019-03-19 [1] CRAN (R 3.6.0)                    
 colorspace    1.4-1     2019-03-18 [1] CRAN (R 3.6.0)                    
 crayon        1.3.4     2017-09-16 [1] CRAN (R 3.6.0)                    
 desc          1.2.0     2018-05-01 [1] CRAN (R 3.6.0)                    
 devtools      2.1.0     2019-07-06 [1] CRAN (R 3.6.1)                    
 digest        0.6.20    2019-07-04 [1] CRAN (R 3.6.1)                    
 dplyr         0.8.3     2019-07-04 [1] CRAN (R 3.6.1)                    
 fansi         0.4.0     2018-10-05 [1] CRAN (R 3.6.0)                    
 fs            1.3.1     2019-05-06 [1] CRAN (R 3.6.0)                    
 ggplot2     * 3.2.0     2019-06-16 [1] CRAN (R 3.6.0)                    
 ggpubr      * 0.2.1.999 2019-07-12 [1] Github (kassambara/ggpubr@9b95e50)
 ggsci       * 2.9       2018-05-14 [1] CRAN (R 3.6.0)                    
 ggsignif    * 0.5.0     2019-02-20 [1] CRAN (R 3.6.1)                    
 glue          1.3.1     2019-03-12 [1] CRAN (R 3.6.0)                    
 gtable        0.3.0     2019-03-25 [1] CRAN (R 3.6.0)                    
 lazyeval      0.2.2     2019-03-15 [1] CRAN (R 3.6.0)                    
 magrittr    * 1.5       2014-11-22 [1] CRAN (R 3.6.0)                    
 memoise       1.1.0     2017-04-21 [1] CRAN (R 3.6.0)                    
 munsell       0.5.0     2018-06-12 [1] CRAN (R 3.6.0)                    
 pillar        1.4.2     2019-06-29 [1] CRAN (R 3.6.1)                    
 pkgbuild      1.0.3     2019-03-20 [1] CRAN (R 3.6.0)                    
 pkgconfig     2.0.2     2018-08-16 [1] CRAN (R 3.6.0)                    
 pkgload       1.0.2     2018-10-29 [1] CRAN (R 3.6.0)                    
 plyr          1.8.4     2016-06-08 [1] CRAN (R 3.6.0)                    
 prettyunits   1.0.2     2015-07-13 [1] CRAN (R 3.6.0)                    
 processx      3.4.0     2019-07-03 [1] CRAN (R 3.6.1)                    
 ps            1.3.0     2018-12-21 [1] CRAN (R 3.6.0)                    
 purrr         0.3.2     2019-03-15 [1] CRAN (R 3.6.0)                    
 R6            2.4.0     2019-02-14 [1] CRAN (R 3.6.0)                    
 Rcpp          1.0.1     2019-03-17 [1] CRAN (R 3.6.0)                    
 remotes       2.1.0     2019-06-24 [1] CRAN (R 3.6.1)                    
 reshape     * 0.8.8     2018-10-23 [1] CRAN (R 3.6.1)                    
 rlang         0.4.0     2019-06-25 [1] CRAN (R 3.6.1)                    
 rprojroot     1.3-2     2018-01-03 [1] CRAN (R 3.6.0)                    
 rstudioapi    0.10      2019-03-19 [1] CRAN (R 3.6.0)                    
 scales        1.0.0     2018-08-09 [1] CRAN (R 3.6.0)                    
 sessioninfo   1.1.1     2018-11-05 [1] CRAN (R 3.6.0)                    
 testthat      2.1.1     2019-04-23 [1] CRAN (R 3.6.1)                    
 tibble        2.1.3     2019-06-06 [1] CRAN (R 3.6.0)                    
 tidyr         0.8.3     2019-03-01 [1] CRAN (R 3.6.0)                    
 tidyselect    0.2.5     2018-10-11 [1] CRAN (R 3.6.0)                    
 usethis       1.5.1     2019-07-04 [1] CRAN (R 3.6.1)                    
 utf8          1.1.4     2018-05-24 [1] CRAN (R 3.6.0)                    
 vctrs         0.2.0     2019-07-05 [1] CRAN (R 3.6.1)                    
 withr         2.1.2     2018-03-15 [1] CRAN (R 3.6.0)                    
 yaml          2.2.0     2018-07-25 [1] CRAN (R 3.6.0)                    
 zeallot       0.1.0     2018-01-28 [1] CRAN (R 3.6.0)                    

[1] C:/Program Files/R/R-3.6.0/library
```

**Comment by kassambara** [comment]
I can't access to your RNAseq data for reproducing and fixing  the problem.

Would you please provide a reproducible example with the `ToothGrowth` demo data set, so that I can help you efficiently?

The following R code works for me:

```r
library(ggpubr)
compare_means(
  len ~ supp, data = ToothGrowth, 
  group.by = "dose", method = "wilcox.test"
  )
```

<pre>
# A tibble: 3 x 9
  dose  .y.   group1 group2       p p.adj p.format p.signif method  
  <fct> <chr> <chr>  <chr>    <dbl> <dbl> <chr>    <chr>    <chr>   
1 0.5   len   OJ     VC     0.0232  0.046 0.023    *        Wilcoxon
2 1     len   OJ     VC     0.00403 0.012 0.004    **       Wilcoxon
3 2     len   OJ     VC     1       1     1.000    ns       Wilcoxon
</pre>


```r
ggboxplot(ToothGrowth, x = "dose", y = "len", color = "supp") +
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x),
    labels = scales::trans_format("log10", scales::math_format(10^.x))
  ) +
  stat_compare_means(aes(group = supp), label = "p")
```
![Rplot](https://user-images.githubusercontent.com/3313355/61129690-3a8f0c80-a4b5-11e9-8ef1-c7488b44593e.jpeg)

**Comment by parrist** [comment]
The Toothgrowth dataset works for me, but my dataset still doesn't work using your script.

Here's a subset of my data.

[RNA-seq_AR.txt](https://github.com/kassambara/ggpubr/files/3387149/RNA-seq_AR.txt)

Thanks for your help.

**Comment by parrist** [comment]
Could the problem be that I have 135 rows in the AR column that are zero?

I do get this warning message when I plot the data:

Warning messages:
1: Transformation introduced infinite values in continuous y-axis 
2: Transformation introduced infinite values in continuous y-axis 
3: Removed 135 rows containing non-finite values (stat_boxplot). 
4: Removed 135 rows containing non-finite values (stat_compare_means).

**Comment by kassambara** [comment]
yes, this is the problem

You are performing the test on the transformed data (log10) when using `stat_compare_means()` in combination with `scale_y_log10()`.

You might find this discussion useful: #36.



If you are not satisfied with the solution in #36 , then:

1. pre-compute stat.test on the original data
2. Create the plot with the transformed y axis
3. Add the pre-computed stat.test on the plot

The code looks like this:


```r

# 0. Data preparation --------------------------------
library(readr)
rnaseq.data <- read_tsv("https://github.com/kassambara/ggpubr/files/3387149/RNA-seq_AR.txt")

# 1. Compute statistical test ------------------------
library(rstatix)  # https://github.com/kassambara/rstatix
stat.test <- rnaseq.data %>%
  group_by(Cohort) %>%
  wilcox_test(AR ~ Sample.type) %>%
  add_significance()
stat.test

# 2. Create boxplot with transformed y scale -----------------
bxp <- ggboxplot(rnaseq.data, x = "Cohort", y = "AR", fill = "Sample.type",palette = "jco") +
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x),
    labels = scales::trans_format("log10", scales::math_format(10^.x))
  ) +
  rotate_x_text() 

# 3. Add stat.test onto the plot --------------------------------
stat.test <- stat.test %>% add_xy_position(x = "Cohort", y.trans = log10)
bxp + stat_pvalue_manual(stat.test, tip.length = 0, label = "p", 
                         y.position = log10(max(rnaseq.data$AR)))
```
![Rplot20](https://user-images.githubusercontent.com/3313355/61151074-590cfc00-a4e5-11e9-8b05-16fdd3e2fe5e.jpeg)

**Comment by parrist** [comment]
Thank you! I will give this a try.

**Comment by parrist** [comment]
Everything works until I get to #3. This is what the plot looks like before adding stat.test:

![AR_test before adding stat_test](https://user-images.githubusercontent.com/52787947/61199322-d13e1200-a6dd-11e9-8011-ca9fe50b6ed7.jpeg)

After adding stat.test to the plot, I get the following warning message and the plot adds Cancer tissue and Normal tissue as a Cohort (with a p-value for the group comparison).

![AR_test after adding stat_test](https://user-images.githubusercontent.com/52787947/61199480-6e00af80-a6de-11e9-8942-7526c3fa5d80.jpeg)

```
Error in add_y_position(., fun = fun, step.increase = step.increase, ...) : 
  unused argument (y.trans = log10)
```

**Comment by kassambara** [comment]
make sure you have installed the latest dev version of `rstatix`

```r
devtools::install_github("kassambara/rstatix", dependencies = FALSE)
```

**Comment by parrist** [comment]
The dev version is now installed, but I still get the same error message.

**Comment by kassambara** [comment]
oh great

**Comment by kassambara** [comment]
install also the latest dev version of ggpubr: 

```r
devtools::install_github("kassambara/ggpubr", dependencies = FALSE)
```

**Comment by parrist** [comment]
Ok!

**Comment by osram90** [comment]
Hi! excellent post.

I have a question.
is there a way to obtain the p-values that are indicate above the boxplots?

**Comment by athenanv** [comment]
Hi, I was also wondering if there was a way to do this (extracting the p-values above the boxplots) and if anyone knew how.
